name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install CMake
        run: |
          sudo apt-get update
          sudo apt-get install cmake

      - name: Set up build directory
        run: mkdir build

      - name: Configure CMake
        run: |
          cd build
          cmake ..

      - name: Build the project
        run: |
          cd build
          cmake --build .

      - name: Save the binary as artifact
        uses: actions/upload-artifact@v4
        with:
          name: audio_compressor
          path: ./build/audio_compressor
